Add initial prompt and language parameters to transcript function
sigaloid/mutter pull request #2
Opened 2024-06-22 08:18 UTC by AllenDang

2024-06-23 14:21 UTC, sigaloid requested changes
Looks good to me otherwise!

2024-06-23 14:21 UTC, sigaloid commented on Cargo.toml
> +whisper-rs = { git = "https://github.com/tazz4843/whisper-rs", branch = "master" }
Can't use the git repo since I publish to crates.io, this should be replaced with just the newest version of whisper-rs

2024-06-25 10:16 UTC, sigaloid commented
Side note: Is the whisper-cpp-log feature no longer used in 0.11? I noticed you took that feature out

2024-06-25 11:45 UTC, AllenDang commented
> Side note: Is the whisper-cpp-log feature no longer used in 0.11? I noticed you took that feature out

Oh, I must missed that, will add it back.

2024-06-26 00:10 UTC, sigaloid approved these changes

2024-06-26 00:10 UTC, merged